language: cpp
compiler: gcc
sudo: true
install:
  - wget https://github.com/catchorg/Catch2/archive/v2.11.1.tar.gz
  - ls -l
  - tar xf Catch2-2.11.1.tar.gz
  - cd Catch2-2.11.1
  - cmake . -DBUILD_SHARED_LIBS=ON
  - make
  - sudo make install
  - cd ..
script:
  - cmake . -GU_BUILD_TESTING=ON
  - make
  - ctest
