language: cpp
compiler: gcc
sudo: true
install:
  - gcc --version
  - cmake --version
  - wget https://github.com/catchorg/Catch2/archive/v2.11.1.tar.gz
  - tar xf v2.11.1.tar.gz
  - cd Catch2-2.11.1
  - cmake CMakeLists.txt -DBUILD_SHARED_LIBS=ON
  - make
  - sudo make install
  - cd ..
script:
  - cmake . -GU_BUILD_TESTING=ON
  - make
  - ctest
