function(display_help_text)
    message("Set GU_BUILD_TESTING to true to build tests. Tests depend on SFML")
    message("Set GU_BUILD_DOC to true to build documentation")
    message("Set GU_BUILD_EXAMPLES to true to build documentation")
endfunction()
